import type { Metadata } from "next";
import { Inter, Open_Sans, Roboto_Slab } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Programa Escolar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
